- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- example/android/app/build.gradle
- example/android/build.gradle
- example/android/gradle/wrapper/gradle-wrapper.properties
update target & compile sdk to 28
add kotlin support to example project
> update gradle plugin to 3.3.2

- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- example/android/app/build.gradle
- example/android/build.gradle
- example/android/gradle/wrapper/gradle-wrapper.properties
Reverts alibaba/flutter_boost#111
> Revert "update gradle plugin to 3.3.2"

- ios/Classes/Adaptor/FLBFlutterEngineOld.m
> flutter 1.9.1 fix

- android/build.gradle
- android/src/main/java/com/idlefish/flutterboost/BoostRegistrar.java
- android/src/main/java/com/idlefish/flutterboost/XAndroidKeyProcessor.java
- android/src/main/java/com/idlefish/flutterboost/XTextInputPlugin.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterActivityAndFragmentDelegate.java
> Feature/flutter 1.9 androidx upgrade

- README.md
- README_CN.md
> Update README.md / README_CN.md

- android/src/main/java/com/idlefish/flutterboost/FlutterBoost.java
在createEngine增加一个回调，方便在使用测做一些事情(打点之类)
> [Android] 在createEngine增加一个回调，方便在使用测做一些事情(打点之类)

- example/lib/simple_page_widgets.dart
- ios/Classes/Engine/FLBFlutterEngine.m
- ios/Classes/container/FLBFlutterViewContainer.m
1. 删除冗余代码
2. fix present页面僵死问题
3. 增加present的测试用例
> 修正present问题并添加测试用例

- android/src/main/java/com/idlefish/flutterboost/Debuger.java
- android/src/main/java/com/idlefish/flutterboost/log/AndroidLog.java
- android/src/main/java/com/idlefish/flutterboost/log/ILog.java
1.增加safeMode字段接口，设置为true后Debugger.exception不再Throw Exception， 默认为false。
2.增加Log实现接口，方便外部获取Boost相关log信息。
> Debugger增强优化

- android/src/main/java/com/idlefish/flutterboost/FlutterBoost.java
FlutterBoost添加sInit字段，作为一个单例，防止被初始化多次
> FlutterBoost防止Init多次

- android/src/main/java/com/idlefish/flutterboost/FlutterBoostPlugin.java
> Result.error参数类型错误

- analysis_options.yaml
- example/lib/main.dart
- example/lib/platform_view.dart
- example/lib/simple_page_widgets.dart
- example/lib/test_input.dart
- example/test/widget_test.dart
- example_swift/lib/main.dart
- example_swift/lib/simple_page_widgets.dart
- example_swift/lib/test_input.dart
- lib/channel/boost_channel.dart
- lib/container/boost_container.dart
- lib/container/boost_page_route.dart
- lib/container/container_coordinator.dart
- lib/container/container_manager.dart
- lib/flutter_boost.dart
- lib/observers_holders.dart
- lib/support/logger.dart
- pubspec.yaml
- test/lib/unit/boost_channel_test.dart
- test/lib/unit/boost_container_test.dart
- test/lib/unit/boost_page_route_test.dart
- test/lib/unit/container_coordinator_test.dart
- test/lib/unit/container_manager_test.dart
- test/lib/unit/flutter_boost_test.dart
- test/lib/unit/page_widget_test.dart
- test/lib/unit/page_widgets.dart
Things which were done in this PR:
* Update the analyzer options with the latest flutter‘s.
* Improved all codes to match the analyzer.
* Update tests at the same time.
**Please stick to the options if you use it, rather than ignored.** Otherwise the usability of the code will be dicreased.
This might include some breaking (by defined generic type). If that happened, please contact me to discuss about it and further update.
Native side also included some bad code format, will improve them separately.
PR做了几件事：
* 更新了编译检查规则与Flutter最新的规则同步；
* 根据规则更改了所有有问题的代码；
* 同步调整了所有的单元测试。
**如果使用了analyzer，请根据它来保持代码质量，而不是忽略它。** 这将让该库的可用性降低。
PR可能包含了一些不兼容的改动（由于泛型指定引起的），如果有任何影响请及时联系我以进行讨论和更新。
原生端也包含一些糟糕的代码格式，将分开对它们进行调整。
> Update format according for flutter's analysis option

- Frequently Asked Question.md
> Update Frequently Asked Question.md

- lib/flutter_boost.dart
只有add没有remove方法，很容易导致内存泄漏，多次监听等问题。
> opt: 添加删除生命周期的方法

- lib/flutter_boost.dart
> fix hotreload时因为类型转换出错带来的白屏问题

- android/src/main/java/com/idlefish/flutterboost/containers/BoostFlutterActivity.java
> fix: BoostFlutterActivity获取activityInfo的lint错误

- android/src/main/java/com/idlefish/flutterboost/XFlutterView.java
- example/lib/main.dart
> android support dark mode

- android/src/main/java/com/idlefish/flutterboost/XFlutterView.java
flutter boost in android miss dark mode code, fix it.
> android dark mode support

- android/src/main/java/com/idlefish/flutterboost/XPlatformPlugin.java
- lib/container/boost_container.dart
修复：
1. Android 进入Flutter页面时StatusBar背景颜色不正确的问题，需要在页面进入时或onResume时调用Platform插件进行刷新
2. 插件复用后的空指针问题
> Task/task v1.12.13 support hotfixes

- example/ios/Runner/AppDelegate.m
- example/ios/Runner/NativeViewController.m
- example/lib/main.dart
- example/lib/simple_page_widgets.dart
- example_swift/lib/simple_page_widgets.dart
embeded 修改为 embedded
recieve 修改为 receive
> 修改部分单词拼写错误

- lib/container/boost_container.dart
- lib/container/boost_page_route.dart
Reverts alibaba/flutter_boost#709
> Revert "Harly fixed migrate 1.17"

- android/src/main/java/com/idlefish/flutterboost/FlutterBoostDelegate.java
- example/android/app/src/main/java/com/idlefish/flutterboost/example/MyApplication.java
- example/android/app/src/main/java/com/idlefish/flutterboost/example/MyFlutterBoostDelegate.java
- example/ios/Podfile.lock
- example/ios/Runner/MyFlutterBoostDelegate.m
- ios/Classes/FlutterBoost.h
- ios/Classes/FlutterBoost.m
- ios/Classes/FlutterBoostPlugin.m
- ios/Classes/container/FBFlutterViewContainer.m
1.对齐双端的基本概念 Delegate都基于接口实现
2.梳理Boost的API以及必要注释，非必要的API放起来讨论
3.对齐OC的语法风格，干掉Java风格的OC代码
> 整理Boost iOS端相关概念

- android/src/main/java/com/idlefish/flutterboost/FlutterBoostPlugin.java
> Android 传递boolean值问题修改

- android/src/main/java/com/idlefish/flutterboost/FlutterBoostPlugin.java
Reverts alibaba/flutter_boost#810
> Revert "Android 传递boolean值问题修改"

- android/src/main/java/com/idlefish/flutterboost/FlutterBoost.java
- android/src/main/java/com/idlefish/flutterboost/FlutterBoostPlugin.java
- android/src/main/java/com/idlefish/flutterboost/FlutterBoostUtils.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostActivity.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostFragment.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterViewContainerObserver.java
- example/android/app/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostView.java
- example/android/app/src/main/java/com/idlefish/flutterboost/example/MainActivity.java
- example/android/app/src/main/java/com/idlefish/flutterboost/example/MyFlutterBoostDelegate.java
- example/android/app/src/main/java/com/idlefish/flutterboost/example/NativePageActivity.java
- example/android/app/src/main/java/com/idlefish/flutterboost/example/TransparencyPageActivity.java
- example/android/app/src/main/java/com/idlefish/flutterboost/example/tab/TabCustomViewActivity.java
- example/android/app/src/main/java/com/idlefish/flutterboost/example/tab/TabMainActivity.java
- lib/boost_lifecycle_binding.dart
1. uniqueId的创建方式与Dart侧保持一致
2. 去掉ContainerShadowNode抽象代码
3. 去掉Flutter容器创建时不必要的engineId参数
> [Android] Native侧代码重构

- android/src/main/java/com/idlefish/flutterboost/FlutterBoost.java
> [Android] 允许业务复用提前创建的引擎

- android/src/main/java/com/idlefish/flutterboost/FlutterBoostPlugin.java
业务可以在引擎setup的Callback后，给dart发送消息，或者发送消息前检查DartExecutor.isExecutingDart，暂时没有必要提供，dart侧ready的回调通知。
> [Android] 明确禁止业务在Dart代码被执行前发送channel消息，避免潜在的消息丢失问题

- android/src/main/java/com/idlefish/flutterboost/containers/ActivityAndFragmentPatch.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostActivity.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostFragment.java
- example/android/app/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostView.java
* 注意：业务需要自己接管handleAppLifecycleStateChanged逻辑
* 详情：https://github.com/alibaba/flutter_boost/commit/173c910ff8ed971eacfa1a263745921ae5cd5689
> [Android] 删除*不再*必要的生命周期通知逻辑

- android/src/main/java/com/idlefish/flutterboost/containers/ActivityAndFragmentPatch.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostActivity.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostFragment.java
- example/android/app/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostView.java
- example/android/app/src/main/java/io/flutter/embedding/android/LifecycleView.java
- example/lib/tab/simple_widget.dart
Reason: 除了Dart侧，引擎Native部分也会根据生命周期事件暂停RequestFrame，
> Revert: "[Android] 删除*不再*必要的生命周期通知逻辑 (#1199)"

- ios/Classes/FlutterBoostPlugin.m
Issues: https://github.com/alibaba/flutter_boost/issues/1206
> [ios] 修复StackInfo.decode 出现NoSuchMethodError异常

- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostActivity.java
- docs/routeAPI.md
* 修改FlutterBoostActivity中的一处手误
> [Android] 补充`页面返回时的参数传递`使用说明

- android/src/main/java/com/idlefish/flutterboost/containers/FlutterActivityLaunchConfigs.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostActivity.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostFragment.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterViewContainer.java
- android/src/main/java/com/idlefish/flutterboost/containers/LifecycleStage.java
* 详情：https://issuetracker.google.com/issues/185693011
> [Android] 解决切后台场景下Android Q生命周期回调异常导致透明弹窗背景不正确问题

- ios/Classes/container/FBFlutterViewContainer.m
- lib/boost_container.dart
在单VC情况下，之前的容器内跳转flutter页面，侧滑退出手势将会将整个容器退出，这样的表现不太符合用户预期
于是做了一下容器数量的监听:
- 当容器内部的 page数量 > 1的时候，将禁止native侧的侧滑手势，此时flutter内部的侧滑手势将会响应
- 当容器内部的page数量 == 1的时候，将允许原生的侧的侧滑，由原生的容器（ViewController）对侧滑进行接管
> [iOS]在单VC下，会根据内部page的个数动态设置是否允许原生容器侧滑退出

- docs/routeAPI.md
- example_new/lib/pages/main_page.dart
- lib/boost_container.dart
这样业务层也能`Navigator.pushNamed`方法进行页面跳转
> 让NavigatorExt接管pushNamed方法

- ios/Classes/container/FBFlutterViewContainer.m
> 提前Container事件监听的注册时机，以及在删除的时候对block进行判空，避免crash

- lib/boost_lifecycle_binding.dart
收敛BoostLifecycleBinding.hasShownPageIds,提供getShownPageSize方法
> 收敛BoostLifecycleBinding.hasShownPageIds,提供getShownPageSize方法

- lib/boost_flutter_router_api.dart
- lib/boost_operation_queue.dart
- lib/flutter_boost_app.dart
> 修复在引擎启动完毕但是flutter侧还没有加载完毕的时候进行操作的函数调用的时序问题

- AUTHORS
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostActivity.java
> [Android]修复特定场景下activity泄漏的问题

- example/lib/case/flutter_rebuild_demo.dart
- example/lib/flutter_page.dart
- example/lib/main.dart
- lib/flutter_boost.dart
- lib/src/boost_cache_widget.dart
示例参考 BoostCacheWidget的使用, flutter_rebuild_demo.dart 测试用例代码
> [flutter] 提供带有缓存的widget组件 BoostCacheWidget,可以解决在push过程中导致页面rebuild的问题

- lib/src/boost_flutter_router_api.dart
- lib/src/flutter_boost_app.dart
原因：时序问题，dart环境还未初始化完成，便开始恢复历史数据
> 修复hot restart导致的黑屏问题

- android/build.gradle
- android/src/main/java/com/idlefish/flutterboost/FlutterBoost.java
- android/src/main/java/com/idlefish/flutterboost/FlutterBoostSetupOptions.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostActivity.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostFragment.java
- example/ios/Runner/GeneratedPluginRegistrant.h
- example/ios/Runner/GeneratedPluginRegistrant.m
- lib/src/boost_container.dart
- lib/src/boost_navigator.dart
- lib/src/flutter_boost_app.dart
RT, the app of xianyu used the flutterboost3. Added some interface and bugfix
> the app of xianyu used the flutterboost3. Added some interface and bugfix

- example/android/app/src/main/AndroidManifest.xml
- example/android/app/src/main/java/com/idlefish/flutterboost/example/Ball.java
- example/android/app/src/main/java/com/idlefish/flutterboost/example/GlRenderer.java
- example/android/app/src/main/java/com/idlefish/flutterboost/example/GlSurface.java
- example/android/app/src/main/java/com/idlefish/flutterboost/example/GlSurfaceFactory.java
- example/android/app/src/main/java/com/idlefish/flutterboost/example/MyApplication.java
- example/android/app/src/main/java/com/idlefish/flutterboost/example/PerfTestActivity.java
- example/android/app/src/main/java/com/idlefish/flutterboost/example/RunBall.java
- example/android/app/src/main/java/com/idlefish/flutterboost/example/RunBallView.java
- example/android/app/src/main/java/com/idlefish/flutterboost/example/RunBallViewFactory.java
- example/android/app/src/main/java/com/idlefish/flutterboost/example/SimpleTextView.java
- example/android/app/src/main/java/com/idlefish/flutterboost/example/TextViewFactory.java
- example/ios/Runner/AppDelegate.m
- example/lib/case/animation_demo.dart
- example/lib/case/bottom_navigation_bar_demo.dart
- example/lib/case/demo_painter.dart
- example/lib/case/native_view.dart
- example/lib/case/native_view_demo.dart
- example/lib/case/platform_view_perf.dart
- example/lib/case/webview_flutter_demo.dart
- example/lib/flutter_page.dart
- example/lib/main.dart
1. 增加复杂的Native动画场景；
2. 支持intent打开测试页面，方便自动化测试；
> [Android] 完善PlatformView测试案例：

- README.md
Corrected the spacing after a period to help with clarity when reading and to fix the grammar mistake.
> Updated Readme for slight spacing error

- CHANGELOG.md
- README.md
- README_CN.md
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostActivity.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostFragment.java
- docs/install.md
issue: #alibaba/flutter_boost/issues/1700
> [Android]恢复detachFromFlutterEngine重载逻辑，解决空指针崩溃问题

- CHANGELOG.md
- README.md
- README_CN.md
- docs/install.md
- example/ios/Runner/GeneratedPluginRegistrant.m
- example/lib/case/animation_demo.dart
- example/lib/case/dual_screen.dart
- example/lib/case/media_query.dart
- example/lib/case/native_view_demo.dart
- example/lib/case/test_input.dart
- example/lib/flutter_page.dart
- example/lib/main.dart
- example/lib/simple_page_widgets.dart
- example/lib/tab/simple_widget.dart
- lib/src/boost_channel.dart
- lib/src/flutter_boost_app.dart
08-19 17:11:17.042 22707 24893 I flutter : The following _CastError was thrown during a scheduler callback:
08-19 17:11:17.042 22707 24893 I flutter : type 'List<(String, Map<dynamic, dynamic>) => Future<dynamic>?>' is not a subtype of type
08-19 17:11:17.042 22707 24893 I flutter : 'List<(String, Map<dynamic, dynamic>?) => Future<dynamic>?>' in type cast
08-19 17:11:17.042 22707 24893 I flutter :
08-19 17:11:17.042 22707 24893 I flutter : When the exception was thrown, this was the stack:
08-19 17:11:17.042 22707 24893 I flutter : #0      FlutterBoostAppState.addEventListener (package:flutter_boost/src/flutter_boost_app.dart:653:11)
08-19 17:11:17.042 22707 24893 I flutter : #1      BoostChannel.addEventListener (package:flutter_boost/src/boost_channel.dart:34:23)
08-19 17:11:17.042 …
> 修复`addEventListener`函数中可能的类型转换错误

- CHANGELOG.md
- example/android/app/build.gradle
- example/lib/case/animation_demo.dart
- example/lib/case/rotation_transition.dart
- example/lib/flutter_page.dart
- example/lib/main.dart
issue: https://github.com/alibaba/flutter_boost/issues/1715, https://github.com/alibaba/flutter_boost/issues/1686
> Add demo for afterimage test

- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostFragment.java
详见：
fix https://github.com/alibaba/flutter_boost/issues/1725
> feat(flutter):对子类开放didFragmentShow和didFragmentHide

- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostFragment.java
link https://github.com/alibaba/flutter_boost/issues/1732
> [Android] 修复FlutterFragment可能会盖住NativeFragment的Bug

- run_pigeon.sh
BTW, we need to manually remove the dependency on Androidx after running the script file.
> Add pigeon commands to script file.

- example/ios/Runner/AppDelegate.m
- example/ios/Runner/Info.plist
- example/ios/Runner/MyFlutterBoostDelegate.m
- example/lib/flutter_page.dart
- example/lib/main.dart
- ios/Classes/FlutterBoostPlugin.h
- ios/Classes/FlutterBoostPlugin.m
- ios/Classes/container/FBFlutterViewContainer.m
> [ios] Use a screen edge pan gesture to go back to the previous page of a non-container page.

- README.md
- doc/api/index.html
- ios/flutter_boost.podspec
Related issue: https://github.com/alibaba/flutter_boost/issues/1757
> [ios] Fixes the warning that the license file does not exist

- lib/src/boost_navigator.dart
pushReplacement 里面调用 push 方法，应该设置泛型，不然会报错
> 处理 pushReplacement 泛型转换错误

- lib/src/boost_container.dart
Related issue: https://github.com/alibaba/flutter_boost/issues/1804
> 修复后退时前一个页面不必要的rebuild的问题

- android/src/main/java/com/idlefish/flutterboost/FlutterBoostPlugin.java
> [Android] fix tab下多个flutterfragment快速切换时，出现不渲染的bug

- CHANGELOG.md
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostActivity.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostFragment.java
- example/android/app/src/main/java/io/flutter/embedding/android/LifecycleView.java
issue: https://github.com/flutter/flutter/issues/140600
> Fix NPE when platform plugin delegate is null

- CHANGELOG.md
- ohos/flutter_boost/src/main/ets/components/messages/FlutterContainer.ets
- ohos/flutter_boost/src/main/ets/components/messages/FlutterPage.ets
- ohos/flutter_boost/src/main/ets/components/messages/NativeRouterApi.ets
- ohos/flutter_boost/src/main/ets/components/messages/NativeRouterApiCodec.ets
- ohos/flutter_boost/src/main/ets/components/plugin/FlutterBoostPlugin.ets
Related issue: https://github.com/alibaba/flutter_boost/issues/1982
> [ohos]修复`hot restart`白屏的问题

- CHANGELOG.md
- example/lib/case/media_query.dart
- example/lib/case/native_view.dart
- example/lib/case/safe_area.dart
- example/lib/case/webview_flutter_demo.dart
- example/lib/flutter_page.dart
- example/lib/main.dart
- example/ohos/entry/src/main/ets/pages/FlutterUIDialog.ets
- example/ohos/entry/src/main/ets/plugins/GeneratedPluginRegistrant.ets
- ohos/flutter_boost/src/main/ets/components/containers/FlutterBoostAbility.ets
- ohos/flutter_boost/src/main/ets/components/containers/FlutterBoostEntry.ets
- ohos/flutter_boost/src/main/ets/components/containers/FlutterViewContainer.ets
NavDestinationMode.DIALOG：默认透明，进出页面栈不影响下层NavDestination的生命周期，不支持系统转场动画
> [ohos]解决从透明弹窗返回后页面假死的问题

- CHANGELOG.md
- example/ohos/entry/src/main/ets/entryability/EntryAbility.ets
- ohos/src/main/ets/components/FlutterBoost.ets
- ohos/src/main/ets/components/plugin/FlutterBoostPlugin.ets
> [ohos]添加前后台事件通知逻辑

- CHANGELOG.md
- example/ohos/entry/src/main/ets/platform_view/SimpleTextView.ets
详情：https://gitee.com/openharmony-sig/flutter_samples/blob/master/ohos/docs/04_development/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8PlatformView.md
> [ohos]适配最新的PlatformView方案

- CHANGELOG.md
- example/ohos/entry/src/main/module.json5
- example/ohos/entry/src/main/resources/base/element/string.json
- example/ohos/entry/src/main/resources/zh_CN/element/string.json
- ohos/src/main/ets/components/containers/FlutterBoostEntry.ets
> [ohos]解决因权限问题从系统剪贴板获取数据失败的问题

- CHANGELOG.md
- example/ohos/entry/src/main/ets/entryability/EntryAbility.ets
- example/ohos/entry/src/main/ets/pages/EntryPage.ets
- example/ohos/entry/src/main/ets/pages/FlutterUIComponent.ets
- example/ohos/entry/src/main/ets/pages/FlutterUIDialog.ets
- example/ohos/entry/src/main/ets/pages/FlutterUIPage.ets
- example/ohos/entry/src/main/ets/pages/NativePage.ets
- example/ohos/entry/src/main/ets/router/RouterModule.ets
- lib/src/flutter_boost_app.dart
- ohos/index.ets
- ohos/src/main/ets/components/containers/FlutterBoostEntry.ets
- ohos/src/main/ets/components/plugin/FlutterBoostPlugin.ets
> [ohos,dart]native侧取消业务自定义实现RouterOptions，优化页面返回传参接口易用性，修复native页面返回flutter页面时传参可能失败的问题
