- ios/flutter_boost.podspec
There have many issues about miss libc++ in the iOS project.
like these: 
- https://github.com/alibaba/flutter_boost/issues/46
- https://github.com/alibaba/flutter_boost/issues/41
- https://github.com/alibaba/flutter_boost/issues/21
- https://github.com/alibaba/flutter_boost/issues/7
Because flutter needs 'libc++' dependencies. But I don't see related dependencies in podspec.
Adding c++ dependencies to podspec will solve this problem, so you don't need to manually add c++ dependencies every time.
> Add libc++ dependency in flutter_boost.podspec

- android/src/main/java/com/idlefish/flutterboost/containers/NewBoostFlutterActivity.java
原生的页面改成flutter页面，一些控件是公共的，比如搜索框，音乐播放的minbar等，需要和原生的页面共用。需要暴露createFlutterView这个接口
> 暴露createFlutterView，供在flutterView add 原生view

- android/src/main/java/com/idlefish/flutterboost/FlutterViewContainerManager.java
平台：Android,  Flutter 1.9.1
分支：feature/flutter_1.9_upgrade
需求场景：
1.flutter界面打开native界面后回传值给上一个界面。
2.flutter界面打开flutter界面后回传值给上一个界面。
问题：
1.flutter界面打开native界面后上一个界面无法获取回传值。
2.flutter界面打开flutter界面后上一个界面无法获取回传值。
原因：
FlutterViewContainerManager中mOnResults 是IContainerRecord的uniqueId与Flutter回调MethodChannel.Result的关联。这个关联出了问题。如下：
A页面(flutter)打开一个新B页面(flutter 或 native)时存入的是新创建的uniqueId与A页面回调的关联。当新界面B结束后A页面(NewBoostFlutterActivity)的onActivityResult会响应，并最终调用FlutterViewContainerManager中的setContainerResult，而这个时候从mOnResults拿取flutter result的回调的key是之前A页面创建的record的uniqueId（即不是新创建的uniqueId）。所以无法获取回调。
修复方案：
打开一个新页面时，关联的uniqueId使用当前栈中的顶部IContainerRecord。
> FlutterViewContainerManager mOnResults 关联错误修复。

- ios/Classes/container/FLBFlutterViewContainer.h
- ios/Classes/container/FLBFlutterViewContainer.m
Hello,  由于之前的PR(#313 )有冲突，并且相关代码也有变动，所以解决方法也有变动了，就把之前的PR关闭了。解决的问题还是之前提到的 #312 
关于改动的一些解释：
由于`FLBFlutterViewContainer`没有指明`designated initializer`，所以默认的`designated initializer`是父类`FlutterViewController`的，即 `- initWithEngine:nibName:bundle:` 和 `- initWithProject:nibName:bundle:`。在 Swift 工程中，如果继承`FLBFlutterViewContainer`做一些封装，就没有办法正确调用到`FLBFlutterViewContainer`的 `- init`，只能调用父类`FlutterViewController`的`designated initializer`，即需要提供一个额外的 Engine，这显然是不想看到的。
> add designated initializer

- android/src/main/java/com/idlefish/flutterboost/NewFlutterBoost.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterActivityAndFragmentDelegate.java
FlutterBoost提供了whenEngineDestory，可以设置All_FLUTTER_ACTIVITY_DESTROY = 1; //所有flutter Activity destory 时，销毁engine。使用过程中发现会导致crash的问题
1.onDestroyView时空指针异常，做了保护处理
2.FlutterBoost初始化的时候注册了页面生命周期的监听，但是销毁引擎的时候没有解注册。打开其他原声页面时，调用Flutter页面壳的OnDestroy，进而关闭了引擎，但是还会监听页面生命周期的变化，在原生页面onStart的时候又创建了一个Engine，但没有完全初始化。再次打开Flutter页面时一些变量没初始化，造成了空指针异常。在boostDestroy做了unregisterActivityLifecycleCallbacks
> 修复使用All_FLUTTER_ACTIVITY_DESTROY时crash的bug

- android/src/main/java/com/idlefish/flutterboost/Utils.java
- lib/container/container_manager.dart
debug模式下statusbar处理异常时不强制抛runtime exception，只打印异常日志；
> 暴露boostcontainer数组；

- android/src/main/java/com/idlefish/flutterboost/containers/BoostFlutterActivity.java
由于NewEngineIntentBuilder内部类的构造无法外部访问(protected),无法继承BoostFlutterActivity自定义，将其改为public。（然而NewEngineFragmentBuilder的构造是public的，改成一致）
> 修改NewEngineIntentBuilder构造的访问权限

- android/build.gradle
- example/android/app/build.gradle
Android 依赖修改为compileOnly方式。解决打包时，递归依赖出现版本号冲突问题。
- support系列：support-v4、appcompat-v7、design
- fastjson
> [Android] Boost修改依赖方式，使用compileOnly方式。解决打包时，递归依赖出现版本号冲突问题。

- android/src/main/java/com/idlefish/flutterboost/XFlutterView.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterSplashView.java
新的注册方式在onAttach时执行attachToView
为了让plugin获取到flutterView，需要执行onFlutterViewAttached。
> 新的注册方式在onAttach时执行attachToView

- android/src/main/java/com/idlefish/flutterboost/XTextInputPlugin.java
修改Webview 多个页面来回切换的时候，在XTextInputPlugin的194行会报空指针异常
> 修改Webview 多个页面来回切换的时候，在XTextInputPlugin的194行会报空指针异常

- ios/Classes/1.5/FLB2FlutterEngine.m
- ios/Classes/1.5/FLB2FlutterViewContainer.m
1. surfaceUpdate会线程等待，且GPU资源会重设,原来的实现过多的触发了这个函数，在低端机上会卡顿。改正后略有缓解
2. 没必要有dummy VC
> 精简代码，避免过多的surfaceUpdate，原因：

- android/src/main/java/com/idlefish/flutterboost/FlutterBoost.java
fix crash：`FlutterBoostPlugin not register yet` if  initFlutter after Activity.OnCreate method，and then called start/stop 
- case: 
- In SplashActivity ,showDialog(in OnCreate method) to check permission, if authorized, then init sdk and jump to SecondActivity)
- solution:
- with this case, will initFlutter on SecondActivity.OnCreate
> [bugfix] fix crash：'FlutterBoostPlugin not register yet'

- android/src/main/java/com/idlefish/flutterboost/FlutterBoost.java
demo 里面 启动改成 FLUTTER_ACTIVITY_CREATED， 
退出到后台，再进入，再点入flutter界面会crash。
在activity的lifecyle，如果没有之前调用doInitialFlutter，不需要主动创建engine
> 只在 doInitialFlutter 调用 createEngine，其他只检查mEngine

- android/src/main/java/com/idlefish/flutterboost/containers/FlutterFragment.java
已在flutter:1.9.1+hotfix.6 && flutter_boost 0.1.66
flutter: v1.12.13+hotfix.8 && flutter_boost master验证通过
> fix多tab情况下，Fragment切换时生命周期未正确同步至Boost的Bug

- example/lib/simple_page_widgets.dart
- example_swift/lib/simple_page_widgets.dart
- lib/flutter_boost.dart
- test/lib/unit/container_manager_test.dart
- test/lib/unit/page_widgets.dart
This fix type cast error handled in 6f8de4f .
The root cause is that dart only returned `Map<dynamic, dynamic>` rather than specific generic type when `invokeMethod` was called. For more specific generic type user can use `cast<String, dynamic>` after the result was returned.
> Fix type cast error with `invokeMethod` method.

- lib/observers_holders.dart
看起来参数没啥用，可以移除掉。
变动会造成 API 不兼容，考虑到升级成本不高就直接移除了
> rm unnecessary params

- .gitignore
- android/src/main/java/com/idlefish/flutterboost/XPlatformPlugin.java
- android/src/main/java/com/idlefish/flutterboost/containers/BoostFlutterActivity.java
- android/src/main/java/com/idlefish/flutterboost/containers/BoostViewUtils.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterActivityAndFragmentDelegate.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterFragment.java
举个例子，Flutter中对Android statusbar中的icon颜色的控制，最终都是通过`SystemChrome.setSystemUIOVerlayStyle()`来进行控制的。但是其内通过成员变量进行了重复调用的优化，也就是说重复的相同调用不会被真正执行，代码如下。
但是，混合栈中，是会多个Activity复用一个引擎，这就会导致在style相同的情况下，`SystemChrome.setSystemUIOVerlayStyle()`只会在第一个FlutterActivity中执行，而无法在第二个FlutterActivity中执行，Api约等于无用。
因此我们可以在每次Flutter页面被push的时候，调用`SystemChrome.restoreSystemUIOverlays()`刷新当前activity的样式。
但是这里有个问题，现在XPlatformPlugin是每个Activity都会new一个的，因此不同的XPlatformPlugin相互之间访问不到对方的currentTheme。也就是说XPlatformPlugin最好也是跟引擎一起被Activity复用。
能被Activity复用就需要解决可能存在的内存泄漏的问题。
> optimized:   把XPlatformPlugin进行复用，解决了statusbar在多个activity中显示异常的问题。

- lib/container/boost_container.dart
目前在framework层不知道`Route`的name，因为flutter boost在构建`Route`时使用的settings没有传入name。 此提交在构建`Route`时使用`BoostContainerSettings`的name，这样在framework可以拿到真正的route name。
> Pass name of BoostContainerSettings to RouteSettings, i.e. framework acknowledge the route name.

- android/src/main/java/com/idlefish/flutterboost/FlutterBoost.java
bugfix : 修复在华为rom上，应用进入后台，点击桌面图标，launcherActivity会被创建，导致flutterboost前台事件失效
> bugfix : 修复在华为rom上，应用进入后台，点击桌面图标，launcherActivity会被创建，导致flutterboost前台事件失效

- android/src/main/java/com/idlefish/flutterboost/XFlutterView.java
修复同时点击两个按钮打开新页面时，导致返回时 flutter 点击事件处理故障的问题。
当双指同时操作页面，且页面有多个按钮可以跳转新页面时，很容易出现该问题。
现象为当同时（或先后把手指放到两个按钮上）跳转新页面后，点击导航栏返回按钮或 back 键返回上一个页面时，上一个页面的按钮点击事件失效，或者 ListView 滚动失去惯性。
> Don't intercept onTouch event when flutter view is not attached.

- lib/container/container_manager.dart
Hello there,
I am from flutter team. We are currently refactoring the HeroControllerScope widget and noticing it breaks one of your test
PR https://github.com/flutter/flutter/pull/60655
test log https://api.cirrus-ci.com/v1/task/6640715738382336/logs/main.log
It turns out the current code in boost_container.dart is outdated and needed to be update. (It is already broken, and the refactor just surface it)
We would like to move away from registering hero controller through Navigator.observer, and use the HeroControllerScope instead.
> [Action Required] Test breakage due to HeroControllerScope refactor

- lib/flutter_boost.dart
1、methodChannel didShowPageContainer 在启动的时候可能不可靠，引擎刚启动method channel可能发不到dart
2、Flutter 1.22之后 rootIsolate启动是异步的， methodChannel didShowPageContainer 发到dart时可能main函数还没跑完，
此时flutter_boost还没初始化完成，路由切换失败，导致白屏。
所以需要boost启动后主动取一次路由信息
> 解决iOS启动第一次打开Flutter页面白屏

- lib/container/boost_container.dart
修复pop时判断result类型错误。
修复后，flutter页面回传值都可以使用
```
Navigator.pop( {"a":"aa"});
```
这种形式，不再需要使用
```
FlutterBoost.singleton.close(xxx)
```
> fix:fix 类型判断错误

- lib/messages.dart
[NativeRouterApi.getStackFromHost -> StackInfo.decode 出现NoSuchMethodError异常](https://github.com/alibaba/flutter_boost/issues/1025)
> 修复StackInfo.decode出现的NoSuchMethodError异常

- ios/Classes/container/FBFlutterViewContainer.m
- lib/page_visibility.dart
关联的issue:https://github.com/alibaba/flutter_boost/issues/1047
备注:
根据[引擎源码](https://github.com/flutter/engine/blob/07e2520d5d8f837da439317adab4ecd7bff2f72d/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L518)来看，内部的`surfaceUpdated`方法在传递`appeared`为true时，会持有当前vc，传入为false的时候会将各个属性置nil,之前发现页面退出的时候没有立刻dealloc，是因为内部还持有本vc的引用，所以无法释放，所以在detachEngine的方法中，先叫一遍`[self.surfaceUpdated:NO]`,释放引用，测试下来vc可以按时dealloc，但是由于`surfaceUpdated`方法可能会引起其他问题，我目前还分析不出，请各位看看有没有什么问题
> 修复iOS端由原生打开flutter页面，再关闭flutter页面时，container容器不能按时dealloc的问题，以及提供全局路由监听的能力

- example/ios/Runner/ReturnDataViewConntroller.h
- example/ios/Runner/ReturnDataViewConntroller.m
- ios/Classes/FlutterBoost.h
- ios/Classes/FlutterBoost.m
由于iOS端没有Android端的setResult接口，所以在boost单例上开了一个接口用于在原生端回传flutter参数
> [iOS]提供从原生页面回传参数到flutter侧的能力

- lib/flutter_boost.dart
- lib/flutter_boost_app.dart
- lib/overlay_entry.dart
1.由于每次push和pop都会build页面栈中所有页面，第一个原因是因为每次refresh都会将所有entry移除再添加，所以会造成重复的页面内所有页面重复build。
2.进行单独的添加和移除后，页面栈内的页面不会重复build，但是仍然会造成顶部的两个页面重复build的情况，也就是A push B，A也会build一次的情况，所以这里给一个链接 ：[https://www.youtube.com/watch?v=Ya3k828Brt4
](解决思路相关链接)，需要将内部overlayEntry的opaque属性设为false，因为官方的路由中有蒙层，而我们没有，而MaterialPageRoute等路由中的opaque属性是在路由动画结束后赋值给蒙层overlayEntry而不是页面overlayEntry的，所以opaque置为false之后，整个逻辑就和flutter自带的相同了
> 解决在push和pop的时候，页面栈所有页面重复build的问题

- example/lib/flutter_page.dart
- example/lib/main.dart
- lib/boost_lifecycle_binding.dart
- lib/page_visibility.dart
给出单独的前台后台的回调接口，并且将Observer类改为非抽象的，业务方需要复写哪个方法就复写哪个方法，不必重写所有方法
> 添加前台后台的回调接口

- android/src/main/java/com/idlefish/flutterboost/FlutterBoostUtils.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostFragment.java
- lib/boost_container.dart
- lib/boost_lifecycle_binding.dart
- lib/flutter_boost_app.dart
- lib/page_visibility.dart
1. 业务同时创建多个FlutterBoostFragment时，uniqueId可能重复，使用UUID替代时间戳
2. 业务可能不通过CachedEngineFragmentBuilder创建FlutterBoostFragment，提供uniqueId默认实现
> [android] FlutterBoostFragment优化

- AUTHORS
- lib/boost_container.dart
在多个Navigator中不允许共享HeroController对象，否则下一个退出时会置空HeroController._navigator对象时，导致上一个页面push一个新页面通过HeroController didPush时报navigator空异常
详细参考https://github.com/flutter/flutter/issues/69392
> FIXED:HeroController.didPush assert(navigator != null) 报空异常

- example3.0/lib/pages/lifecycle_test_page.dart
- lib/boost_lifecycle_binding.dart
- lib/flutter_boost_app.dart
- lib/logger.dart
- lib/page_visibility.dart
重要解决了在页面没创建之前就发出onPageShow事件，从而造成第一次show时间无法接收的现象
目前情况：双端带容器push or 非容器push新页面，第一次show均能接收到
> 确保onPageShow事件能够在页面创建的时候调用到

- example3.0/ios/Runner/BoostDelegate.swift
- example3.0/lib/main.dart
- example3.0/lib/pages/lifecycle_test_page.dart
- example3.0/lib/pages/main_page.dart
- example3.0/lib/pages/replacement_page.dart
- ios/Classes/container/FBFlutterViewContainer.m
- lib/boost_lifecycle_binding.dart
- lib/boost_navigator.dart
- lib/flutter_boost_app.dart
- 之前的pop逻辑：在id不为空，且id属于在顶部container的非顶部页面的时候，移除会失效，具体看pop修改代码即可-   
- 2.findContainerById进行了修改，原因在于，在remove了container的第一个页面之后，如果单单靠page的pageInfo的id来寻找container就有了问题，所以，现在的思路是先从container的pageInfo找id，如果找到了，返回，如果找不到，再到page里面去找
> BoostNavigator添加pushReplacement方法，同时修复pop和findContainerById的逻辑

- android/src/main/java/com/idlefish/flutterboost/FlutterBoost.java
- android/src/main/java/com/idlefish/flutterboost/FlutterBoostPlugin.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterContainerManager.java
- example3.0/lib/main.dart
- ios/Classes/container/FBFlutterViewContainer.m
- ios/Classes/container/FBLifecycle.h
- ios/Classes/container/FBLifecycle.m
- lib/boost_lifecycle_binding.dart
- lib/flutter_boost_app.dart
上一次改了Flutter AppLifecycle的实现，基于前后台来控制。目前看可能基于容器数量是一个更好的方案，之前iOS也是这样实现的，有容器就resume，没有任何容器就pause。
> 让容器数量决定Flutter的resume和pause状态，而不是前后台

- ios/Classes/FlutterBoost.m
调整 Flutter Engine 初始化流程，避免使用异步方式产生插件注册时序问题
> 调整 Flutter Engine 初始化流程，避免使用异步方式产生插件注册时序问题

- example/lib/case/media_query.dart
- example/lib/case/transparent_widget.dart
- example/lib/flutter_page.dart
- lib/boost_container.dart
- lib/boost_flutter_router_api.dart
- lib/flutter_boost_app.dart
* 1. 通过BoostNavigator打开的内部路由，也可通过原生Navigator.pop关闭，并且正确传递返回值
* 2. 解决内部路由场景下pending Completer可能泄漏的问题
> 重构内部路由Pop时的结果回传逻辑

- lib/overlay_entry.dart
关联issue：#1246
先说现象（我只看了iOS的），原生容器可以正常dealloc，但是flutter层的dispose并没有调用，像issue说的那样，下一次push的时候才会调用dispose。
之前改过一次，但是我认为其实有点问题，之前的`hasScheduledFrame`和`framesEnabled`变量的生成在overlay进行insert/remove之前进行记录，但是我认为应该在overlay进行insert/remove之后才对这两个变量进行记录才是合适的，因为overlay的insert/remove方法会调用内部的setState，而setState才会对vsync信号进行订阅，从而保证触发`SchedulerBinding.instance.scheduleWarmUpFrame();`的逻辑，所以如果这两个变量，也就是`hasScheduledFrame`和`framesEnabled`在overlay进行操作之前就记录的话，其实就走不到if判断里面的`SchedulerBinding.instance.scheduleWarmUpFrame();`逻辑了。当然，如果更暴力点，直接无需判断直接调`SchedulerBinding.instance.scheduleWarmUpFrame();`貌似也没有问题
> 修复刷帧逻辑bug，确保刷帧正常进行，从而让State正常dispose

- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostActivity.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostFragment.java
修复 当用 FlutterBoostActivity容器打开一个flutter page页面后，在flutter页面请求权限，FlutterBoostActivity收不到请求权限结果
> [android] 修复FlutterBoostActivity和FlutterBoostFragment接收不到请求权限结果的bug

- android/src/main/java/com/idlefish/flutterboost/FlutterBoost.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostActivity.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostFragment.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterContainerManager.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterViewContainer.java
- example/android/app/build.gradle
- example/android/app/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostView.java
- example/lib/case/webview_flutter_demo.dart
issue: #1274 、#1205
* 之前：只要FlutterViewContainer收到onResume/onPause事件（包括切后台，打开Native页面），都会执行引擎的attach/detach操作
* 现在：只有引擎的FlutterView真正发生切换时，才执行attach/detach操作（前后台事件和Native页面引起的onResume/onPause回调，并没有FlutterView的切换）
* 注：将detach操作从旧Activity的onPause推迟到新Activity的onResume时，两个Activity间的切换动画会闪黑一下（为了不修改引擎，暂时通过Java反射修复）。
> [Android] 解决特定场景下半透明弹窗背景黑/白屏、传参丢失、请求权限失败，以及image_picker插件不可用等问题

- ios/Classes/FlutterBoost.m
- ios/Classes/Options.h
- ios/Classes/Options.m
关联issue：
#1272 
#1243 
在没有开启引擎预热的情况，大多数情况第一次打开flutter页面会出现短暂的白屏/黑屏，以及字体大小跳动的情况，这里在启动的时候扔一个空的FlutterVC让engine去画一下，达到引擎预渲染的目的，整个逻辑比较简单，也不需要修改任何dart侧的逻辑，只需要在boost初始化启动的时候根据参数判断是否需要预热，目前只做了ios端。
预热效果前后对比（模式为release，工程为example_new）
关闭引擎预热
https://user-images.githubusercontent.com/49340347/132168968-1d0441c2-6504-48a6-8332-8c2cdaa5f4b2.mp4
开启预热
https://user-images.githubusercontent.com/49340347/132168884-49442e1b-a0ba-4c89-a6c3-881ec81b9760.mp4
> 引擎预热，默认开启预热功能,目前已完成iOS端

- ios/Classes/container/FBFlutterViewContainer.m
- lib/boost_container.dart
之前是用统一的key来对单容器，多page的情况进行侧滑手势的监听控制，但是会带来一个问题，就是如果存在多个flutterBoostContainer，那么这些container都会接收到事件，这是不符合期望的，所以，修改后，只有当前page对应的那个vc才会接收到事件，形成对应关系
> 根据容器内部的侧滑手势的事件发送key的优化，避免多个vc同时接收到事件

- example_new/ios/Runner/AppDelegate.swift
- example_new/lib/main.dart
- ios/Classes/container/FBFlutterViewContainer.m
关联issue：
https://github.com/alibaba/flutter_boost/issues/1358
在有flutter tab的情况下，如果willMoveToParentViewController进行调用，那么初始化的内部数据会有不同步问题，造成点击最后一个tab会出现白屏（初始化路由页面）的问题。
目前willMoveToParentViewController会造成一个页面显示的时候两次push，比较冗余
> 增加tab模式的example，删除iOS端无用的生命周期，避免初始化阶段进行push，造成初始化情况下tab白屏问题

- example_new/ios/Runner/Controllers/HomeViewController.swift
- example_new/lib/pages/main_page.dart
- lib/boost_channel.dart
- lib/boost_container.dart
- lib/boost_lifecycle_binding.dart
在container之间跳转的时候，也同步动态手势的pop的配置
避免在flutter（不带container） -> flutter（不带container） -> flutter（带container） 的时候，最后一个container的手势侧滑失效，而在返回上一个container的时候，也会根据上一个container的内部flutter page数量，动态设置侧滑手势
> 将控制iOS手势的方法收口到BoostChannel作为通用方法，以及在container的show的监听中做手势的动态禁用和启用

- lib/src/flutter_boost_app.dart
popUntil使用containers列表不能保证顺序性，在同步popRoute过程会导致出现containers的乱序。需要通过提前clone队列进行保证
> popUntil使用containers列表不能保证顺序性，在同步popRoute过程会导致出现containers的乱序。需要通过提前clone队列进行保证

- lib/src/boost_flutter_router_api.dart
- lib/src/container_overlay.dart
- lib/src/flutter_boost_app.dart
原因如下：
在用户没有设置初始路由的情况下，应用启动以后立即打开一个Flutter页面，
如果该消息到达dart时：FlutterBoostAppState已经调用initState，
但是addPostFrameCallback还未执行，就会出现目标页面与默认的初始路由顺序颠倒的问题。
> [dart] 修复应用启动首次访问flutter页面白屏问题

- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostActivity.java
在super.onDestroy之后访问FlutterEngine，会出现空指针。
/cc @pkuyaoyao
> [Android] 修复FlutterEngine空指针异常

- AUTHORS
- android/src/main/java/com/idlefish/flutterboost/FlutterBoostDelegate.java
- android/src/main/java/com/idlefish/flutterboost/FlutterBoostPlugin.java
- example/android/app/src/main/java/com/idlefish/flutterboost/example/MyFlutterBoostDelegate.java
抛出Android端popRoute代理回调，用于处理自定义pop逻辑。例如混合栈中自定义出栈逻辑
> feat: Android抛出popRoute代理回调

- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostFragment.java
我司App支持黑白两色皮肤，关闭Flutter引擎针对Android一端自动修改状态栏颜色功能后，FlutterBoostFragment页面在白色皮肤下展示了白色的状态栏图标。
由于引擎自动修改状态栏颜色不可控，故我们关闭了Flutter引擎中自动改变状态栏颜色的逻辑，但是发现关闭Flutter引擎中的自动改变状态栏逻辑后，状态栏颜色依然不可控，最终排查定位到，在FlutterBoostFragment#onResume方法中，调用了platformPlugin.updateSystemUiOverlays()方法导致状态栏显示异常。
详情见issues：https://github.com/alibaba/flutter_boost/issues/1564
> fix(Android):FlutterBoost开启FlutterBoostFragment页面导致状态栏颜色异常

- AUTHORS
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostActivity.java
- example/android/app/src/main/java/com/idlefish/flutterboost/example/MyFlutterBoostDelegate.java
发现boost android里存在FlutterBoostActivity内存泄露，经反复测试发现必现路径：工程自带的example也能重现：
native页面 -> 点open flutterPage(算Flutter首页) -> flutterRebuildDemo (算A页面) -> pushWithContainer (算B页面),
陆续关闭页面，从B 到 A，再Back A 到flutter首页，此时A activity泄露。
经分析，acvitiy onResume()里的detachFromEngineIfNeeded()调用，仅适用于页面返回时，deatch不需要的旧页面。
但新页面打开时，由于flutter引擎flutterView.detachFromFlutterEngine()内部做了isAttachedToFlutterEngine判断，此时deatch底部的页面无效，因为onCreate时已经创建了新的flutterView，因此在super.onCreate前加一个detach，此处刚好适应的是打开新页面的时机。
这样打开新页面，从旧页面返回就都有有效的detach了。
> 修复flutter首页打开A页面，打开B页面，返回到首页后内存泄露问题

- CHANGELOG.md
- android/src/main/java/com/idlefish/flutterboost/FlutterBoostPlugin.java
- example/android/app/src/main/java/com/idlefish/flutterboost/example/NativePageActivity.java
- example/lib/flutter_page.dart
- lib/src/boost_interceptor.dart
- lib/src/flutter_boost_app.dart
对于Android Native页面，在onActivityResult回调中处理即可（[#pull/1108](https://github.com/alibaba/flutter_boost/pull/1108) 合入后不再需要该兜底方案）。
> [Android] 去掉不必要的兜底方案，解决Native页面返回值丢失的问题

- AUTHORS
- lib/src/flutter_boost_app.dart
onPostPush 和 onPostPush 中
1. 用户 reslove 之后，不应该强转成 BoostInterceptorOption
2. 用户 在方法中不调用 handler，应该也算是 终止
> 修复  onPostPush 和 onPostPush 类型强转失败

- AUTHORS
- android/src/main/java/com/idlefish/flutterboost/FlutterBoostPlugin.java
[Android] 修复Java层重写FlutterBoostDelegate中的popRoute方法后，导致dart层popUntil方法失效，只能回退1层的bug
#1710
> [Android]fix popUntil not working

- CHANGELOG.md
- android/src/main/java/com/idlefish/flutterboost/FlutterBoostPlugin.java
- example/lib/case/rotation_transition.dart
[注意] 应用「务必」确保前后台通知事件（onBackground/onForeground）的准确性，必要时通过dispatchBackForegroundEvent接管，否则可能出现页面假死现象；
相关问题：https://github.com/alibaba/flutter_boost/issues/1715, https://github.com/alibaba/flutter_boost/issues/1686
> [Android] 与纯Flutter应用生命周期行为保持一致：应用切换到后台时，暂停帧调度，解决动画残影的问题

- android/src/main/java/com/idlefish/flutterboost/FlutterBoostPlugin.java
* fix popUntil not working
[Android] 修复Java层重写FlutterBoostDelegate中的popRoute方法后，导致dart层popUntil方法失效，只能回退1层的bug
> [Android]fix popUntil not working (#1718)

- lib/src/flutter_boost_app.dart
> 开放FlutterBoostAppState中的_containers

- AUTHORS
- android/src/main/java/com/idlefish/flutterboost/FlutterBoostPlugin.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostActivity.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostFragment.java
- example/android/app/build.gradle
- example/android/app/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostView.java
业务同学反馈，切换FlutterBoostFragment时偶尔闪现上一个页面。
猜测的可能原因是，Native端的容器切换与Dart侧的切换不同步导致。也就是Native先切换过去了，显示了新页面，但是dart还没有切换，刷了一帧当前页面后，才切换到新页面。
> [Android] 解决FlutterBoostFragment切换时可能闪现上一个页面的问题

- example/lib/main.dart
如果自定了`appBuilder`，需要将传入的参数添加到widget层次结构中去，否则会导致FluttBoost初始化失败。
Related issue: https://github.com/alibaba/flutter_boost/issues/1790
> 增加自定义`appBuilder`示例

- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostActivity.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostFragment.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterContainerManager.java
将前一个容器从引擎detach的时机「推迟」到新容器的Dart页面push完成后，开始attach引擎之前，以便更新页面，避免呈现横/竖屏切换前的旧图像
> [Android] 解决横/竖屏切换后，后退时闪现页面被拉伸（或压缩）的问题

- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostActivity.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostFragment.java
Reason: 该修复方案可能导致后退截图可能不正确，即当前页面的截图与前一个页面的截图相同。该问题不能通过调整attch/detach的时机进行解决，暂时回滚。
> Revert: "[Android] 解决横/竖屏切换后，后退时闪现页面被拉伸（或压缩）的问题 (#1857)"

- ios/Classes/FlutterBoostPlugin.m
将completion放在FlutterBoostRouteOptions参数里让业务回调，容易被业务遗漏。当前对回调时机的精度要求不高，回调直接在内部处理，避免遗漏。
Related issue: https://github.com/alibaba/flutter_boost/issues/1867
> [ios] 解决pop传参不能返回的问题

- lib/src/boost_container.dart
- lib/src/flutter_boost_app.dart
Reverts alibaba/flutter_boost#1865
该 PR会引发[新问题](https://github.com/alibaba/flutter_boost/pull/1865#issuecomment-1683253289
)，先暂时回滚。
另外，https://github.com/alibaba/flutter_boost/issues/1863 问题的原因可能是，FlutterBoost为了无缝兼容原生的Navigator，混合使用了命令式和声明式两种路由API，引起了同步问题。
> Revert "fix #1863"

- CHANGELOG.md
- lib/src/page_visibility.dart
Note: Dart 3.0 no longer allows classes to be used as mixins by default.
Fixes: https://github.com/alibaba/flutter_boost/issues/1947
> Add `mixin` modifier to avoid breaking user codes.

- CHANGELOG.md
- android/src/main/java/com/idlefish/flutterboost/FlutterBoostPlugin.java
- example/ios/Podfile
- ios/Classes/container/FBLifecycle.m
- lib/src/boost_flutter_binding.dart
- lib/src/flutter_boost_app.dart
Fix the following exception:
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════ The following assertion was thrown during a platform message callback: Invalid lifecycle state transition generated from AppLifecycleState.resumed to AppLifecycleState.detached (generated [AppLifecycleState.detached]) 'package:flutter/src/services/binding.dart':
Failed assertion: line 296 pos 12: '(){
AppLifecycleState? starting = previousState;
for (final AppLifecycleState ending in stateChanges) {
if (!_debugVerifyLifecycleChange(starting, ending)) {
return false;
}
starting = ending;
}
return true;
}()'
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you …
> Adapt to the official engine's App Lifecycle state changes.

- android/src/main/java/com/idlefish/flutterboost/FlutterBoostUtils.java
- android/src/main/java/com/idlefish/flutterboost/containers/ContainerThemeMgr.java
- android/src/main/java/com/idlefish/flutterboost/containers/FlutterBoostActivity.java
- example/lib/case/system_ui_overlay_style.dart
#1870 #1976 
主要原因是Flutter层的`system_chrome.dart`的`setSystemUIOverlayStyle`方法中做了新老style的对比，只有发生变化的时候，才会调用Native方法进行设置，这就导致使用新Container模式打开Flutter页面，会因为上述原因，不会将新的Container的样式设置为Flutter层希望的，而是使用了Activity默认的。
所以解决的问题点就是在Native层，打开新容器时，将最新的样式设置给新容器。
记录和维护一个Container-SystemUiOverlayStyle绑定关系的Map，当打开新容器时，将上个页面的Style拿出，设置给新容器即可。然后当容器销毁时，从Map中移除绑定关系。
有一个特殊的注意点，那就是从Flutter上设置SystemUiOverlayStyle，反馈到Native的方法中，只会对非null的值进行处理，也就意味着，这里实际上是有一个`在之前Style基础上，仅对非null参数做UI更新`的`隐性的merge`逻辑。一旦从Flutter层触发后，`platformPlugin`中的`currentTheme`其实就是一个不完整的Style，它内部仅仅只有最后一次更改的那几个参数，如果记录这个style，那么就会导致下次打开新容器时，样式又出现问题。所以代码逻辑中，在更新Map之前，Native需要有一个Merge Style的逻辑，保证持有的Style是完整的。
此外，当仅有的一个Flutter容器被销毁后，再打开新的，因为没有`上一个容器的Style`，所以不能还原。因此针对这种case，做特殊处理，将最后关闭的容器的Style记录下来。
使用`system_ui_overlay_style.dart`进行测试。测试要点：1. …
> [Android]fix SystemUiOverlayStyle设置失效

- CHANGELOG.md
- example/ohos/entry/src/main/ets/entryability/EntryAbility.ets
- example/ohos/entry/src/main/ets/pages/FlutterUIComponent.ets
- example/ohos/entry/src/main/ets/pages/FlutterUIDialog.ets
- example/ohos/entry/src/main/ets/pages/FlutterUIPage.ets
- ohos/src/main/ets/components/FlutterBoostDelegate.ets
- ohos/src/main/ets/components/containers/FlutterBoostEntry.ets
- ohos/src/main/ets/components/plugin/FlutterBoostPlugin.ets
这里提供了两种方式：
1. 在FlutterBoostDelegate中提供popRoute接口：业务自己处理页面出栈逻辑，则返回`true`;
2. 在FlutterBoostEntry的构造函数中提供可选的onPop回调接口，如果该参数不为空，则执行该回调逻辑；
> [ohos] 允许业务自己实现页面出栈逻辑
